import xml.etree.ElementTree as ET
import os

STRING_DEFINITIONS = [
    # General & Actions
    ("app_name", "FiveLight"),
    ("action_cancel", "Cancel"),
    ("action_done", "Done"),
    ("action_save", "Save"),
    ("action_close", "Close"),
    ("action_delete", "Delete"),
    ("action_retry", "Retry"),
    ("action_back", "Back"),
    ("action_next", "Next"),
    ("action_skip", "Skip"),
    ("action_continue", "Continue"),
    ("action_confirm", "Confirm"),
    ("action_sign_out", "Sign Out"),
    ("action_clear", "Clear"),
    ("action_search", "Search"),
    ("action_edit", "Edit"),
    ("action_add", "Add"),
    ("action_reset", "Reset"),
    ("action_copy", "Copy"),
    ("action_share", "Share"),
    ("action_download", "Download"),
    ("action_refresh", "Refresh"),
    ("action_dismiss", "Dismiss"),
    ("action_begin_journey", "Begin your journey"),
    ("action_get_started", "Get Started"),
    ("action_enable_notifications", "Enable Notifications"),

    # Nav
    ("nav_home", "Home"),
    ("nav_qibla", "Qibla"),
    ("nav_quran", "Quran"),
    ("nav_tasbeeh", "Tasbeeh"),
    ("nav_explore", "Explore"),
    ("nav_calendar", "Calendar"),
    ("nav_dua", "Dua"),
    ("nav_adhkar", "Adhkar"),
    ("nav_names", "Names of Allah"),

    # Prayers
    ("prayer_fajr", "Fajr"),
    ("prayer_sunrise", "Sunrise"),
    ("prayer_dhuhr", "Dhuhr"),
    ("prayer_asr", "Asr"),
    ("prayer_maghrib", "Maghrib"),
    ("prayer_isha", "Isha"),
    ("prayer_qiyam", "Qiyam / Tahajjud"),
    ("prayer_tahajjud", "Tahajjud"),
    ("prayer_ishraq", "Ishraq"),
    ("prayer_duha", "Duha / Chasht"),
    ("prayer_awwabin", "Awwabin"),

    # Prelude
    ("prelude_tagline", "Your day, illuminated."),
    ("prelude_prayer_title", "Begin with what matters."),
    ("prelude_prayer_subtitle", "Your prayers, your day, beautifully in rhythm."),
    ("prelude_remembrance_title", "Stay close."),
    ("prelude_remembrance_subtitle", "Small moments of remembrance, throughout your day."),
    ("prelude_verse_translation", "\"Indeed, in the remembrance of Allah do hearts find rest.\""),
    ("prelude_qibla_title", "Find your direction."),
    ("prelude_qibla_subtitle", "Accurate Qibla and prayer guidance, wherever you are."),
    ("prelude_personalization_title", "Make it yours."),
    ("prelude_personalization_subtitle", "Your worship, your progress, your FiveLight."),
    ("prelude_closing_title", "Made for your journey."),
    ("prelude_frag_prayer_rhythm", "Prayer Rhythm"),
    ("prelude_frag_quran_verses", "Quran & Verses"),
    ("prelude_frag_dhikr_dua", "Dhikr & Dua"),
    ("prelude_frag_spiritual_goals", "Spiritual Goals"),
    ("prelude_frag_personal_log", "Personal Log"),
    ("prelude_frag_cloud_sync", "Cloud Sync"),
    ("cd_prelude_opening_scene", "FiveLight Opening scene"),
    ("cd_prelude_prayer_scene", "Prayer timeline scene"),
    ("cd_prelude_remembrance_scene", "Remembrance scene"),
    ("cd_prelude_qibla_scene", "Qibla compass scene"),
    ("cd_prelude_personalization_scene", "Personalization scene"),
    ("cd_prelude_closing_scene", "Five Lights closing scene"),
    ("cd_next_prelude_page", "Next prelude page"),
    ("cd_begin_journey", "Begin journey"),

    # Auth & Onboarding
    ("prelogin_title", "Keep your journey with you."),
    ("prelogin_subtitle", "Sign in with your account to automatically sync your prayers, Quran bookmarks, and custom Dhikr across all your devices."),
    ("prelogin_benefit_cloud_sync", "Cloud Synchronization"),
    ("prelogin_benefit_cloud_sync_desc", "Seamlessly access your logs and daily progress on any device."),
    ("prelogin_benefit_backup", "Private & Secure Backup"),
    ("prelogin_benefit_backup_desc", "Your spiritual records and streaks are preserved safely in the cloud."),
    ("prelogin_benefit_cross_device", "Cross-Device Continuity"),
    ("prelogin_benefit_cross_device_desc", "Pick up right where you left off, from your phone or tablet."),
    ("prelogin_sign_in_or_register", "Sign In or Register"),
    ("prelogin_continue_as_guest", "Continue as Guest"),
    ("auth_login_to_continue", "Log In to Continue"),
    ("auth_login_subtitle", "Sign in or create an account to keep everything in sync."),
    ("auth_login_with_email", "Login with Email"),
    ("auth_login_with_google", "Login with Google"),
    ("auth_dont_have_account", "Don't have an account?"),
    ("auth_register_new_account", "Register New Account"),
    ("auth_welcome_back", "Welcome back"),
    ("auth_login_title", "Login to your account"),
    ("auth_email_address", "Email Address"),
    ("auth_email_placeholder", "Enter your email address"),
    ("auth_password", "Password"),
    ("auth_password_placeholder", "Enter your password"),
    ("auth_remember_me", "Remember me"),
    ("auth_forgot_password", "Forgot password?"),
    ("auth_login_button", "Login"),
    ("auth_have_issue", "Have an Issue in Login?"),
    ("auth_create_account_title", "Create Your Account"),
    ("auth_create_account_eyebrow", "Start your spiritual journey with FiveLight"),
    ("auth_full_name", "Full Name"),
    ("auth_full_name_placeholder", "Enter your full name"),
    ("auth_confirm_password", "Confirm Password"),
    ("auth_confirm_password_placeholder", "Confirm your password"),
    ("auth_already_have_account", "Already have an account?"),
    ("auth_error_name_required", "Full name is required"),
    ("auth_error_email_required", "Email is required"),
    ("auth_error_email_invalid", "Please enter a valid email address"),
    ("auth_error_password_required", "Password is required"),
    ("auth_error_password_short", "Password must be at least 6 characters"),
    ("auth_error_password_mismatch", "Passwords do not match"),
    ("auth_google_signin_failed", "Google Sign-In failed"),
    ("auth_verification_title", "Verify your email"),
    ("auth_verification_subtitle", "We've sent a verification link to your email address. Please open the email and tap the verification link to continue."),
    ("auth_check_inbox", "Check your inbox"),
    ("auth_verify_button", "I've Verified My Email"),
    ("auth_resend_email", "Resend Verification Email"),
    ("auth_verification_success", "Email successfully verified!"),
    ("auth_verification_not_verified", "Your email is not verified yet. Please check your inbox, click the verification link, and try again."),
    ("auth_verification_resend_success", "Verification email sent. Please check your inbox."),
    ("auth_reset_password_sent", "Password reset link sent to your email."),
    ("cd_email_login", "Email Login"),
    ("cd_google_logo", "Google Logo"),
    ("cd_show_password", "Show password"),
    ("cd_hide_password", "Hide password"),

    # Setup FiveLight
    ("setup_welcome_eyebrow", "WELCOME"),
    ("setup_title", "Make FiveLight yours."),
    ("setup_subtitle", "A few quick choices and FiveLight will be ready for your daily rhythm."),
    ("setup_city_step_title", "Where are you located?"),
    ("setup_city_step_desc", "Select your city to get exact prayer times and Qibla direction."),
    ("setup_calc_step_title", "Calculation Method"),
    ("setup_calc_step_desc", "Choose the prayer calculation standard used in your region."),
    ("setup_madhab_step_title", "Asr Calculation (Madhab)"),
    ("setup_madhab_step_desc", "Standard (Shafi'i, Maliki, Hanbali) or Hanafi timing."),
    ("setup_theme_step_title", "Appearance"),
    ("setup_theme_step_desc", "Choose your preferred visual theme."),
    ("setup_complete_button", "Get Started"),
    ("setup_recommended_badge", "Recommended"),

    # Home Screen & Prayer Cards
    ("home_next_prayer", "Next Prayer"),
    ("home_time_remaining", "%1$s remaining"),
    ("home_completed", "Completed"),
    ("home_mark_prayed", "Mark as prayed"),
    ("home_prayed", "Prayed"),
    ("home_missed", "Missed"),
    ("home_qada_tracker", "Qada Tracker"),
    ("home_qada_remaining", "%1$d missed"),
    ("home_make_up_prayer", "Make up prayer"),
    ("home_context_prep", "Time for %1$s is approaching"),
    ("home_context_now", "It is time for %1$s"),
    ("home_context_night", "Night is coming"),
    ("home_feature_continue_reading", "Continue Reading"),
    ("home_feature_recently_read", "Recently Read"),
    ("home_feature_reflection", "Reflection of the Day"),
    ("home_feature_nafl_prayers", "Voluntary (Nafl) Prayers"),
    ("home_feature_weekly_overview", "Weekly Prayer Overview"),
    ("home_feature_friday_moment", "Friday Mubarak"),
    ("home_feature_quran_lens", "Quran Lens"),
    ("home_feature_prayer_journey", "Prayer Journey"),
    ("home_feature_tonight", "Tonight / Night is Coming"),
    ("home_feature_next_opportunity", "Next Opportunity"),
    ("home_feature_quiet_mode", "Quiet Mode"),
    ("home_feature_prayer_prep", "Contextual Next Action & Prep"),

    # Qibla Screen
    ("qibla_title", "Qibla Compass"),
    ("qibla_heading", "%1$d°"),
    ("qibla_facing_kaaba", "You are facing the Kaaba"),
    ("qibla_rotate_device", "Rotate device towards the Qibla pointer"),
    ("qibla_sensor_unreliable", "Low compass accuracy. Calibrate by waving your device in a figure 8."),
    ("qibla_sensor_unavailable", "Compass sensor not available on this device."),
    ("qibla_calibrate", "Calibrate"),
    ("cd_qibla_dial", "Qibla Compass Dial"),

    # Tasbeeh Screen
    ("tasbeeh_title", "Tasbeeh"),
    ("tasbeeh_reset_counter", "Reset Counter"),
    ("tasbeeh_target", "Target: %1$d"),
    ("tasbeeh_target_reached", "Target Reached!"),
    ("tasbeeh_custom_dhikr", "Custom Dhikr"),
    ("tasbeeh_add_dhikr", "Add Custom Dhikr"),
    ("tasbeeh_edit_dhikr", "Edit Dhikr"),
    ("tasbeeh_delete_dhikr", "Delete Dhikr"),
    ("tasbeeh_restore_defaults", "Restore Default Dhikrs"),
    ("tasbeeh_total_count", "Total: %1$d"),
    ("tasbeeh_history", "Dhikr History"),
    ("tasbeeh_vibration_toggle", "Vibration Feedback"),
    ("tasbeeh_sound_toggle", "Tap Sound"),
    ("tasbeeh_volume_keys_toggle", "Dhikr Volume Button Controls"),
    ("tasbeeh_volume_keys_desc", "Use volume keys to count Dhikr"),
    ("tasbeeh_tap_to_count", "Tap anywhere to count"),
    ("tasbeeh_count_decremented", "Count decremented"),
    ("tasbeeh_count_reset", "Counter reset"),
    ("tasbeeh_no_history", "No Dhikr recorded today yet."),

    # Quran Screen & Reader & Explorer
    ("quran_title", "The Noble Quran"),
    ("quran_search_surahs", "Search surahs, verses..."),
    ("quran_all_surahs", "All Surahs"),
    ("quran_bookmarks", "Bookmarks"),
    ("quran_last_read", "Last Read"),
    ("quran_surah_number", "Surah %1$d"),
    ("quran_verses_count", "%1$d verses"),
    ("quran_revelation_meccan", "Meccan"),
    ("quran_revelation_medinan", "Medinan"),
    ("quran_download_surah", "Download Audio"),
    ("quran_delete_download", "Delete Downloaded Audio"),
    ("quran_download_all", "Download All 114 Surahs"),
    ("quran_downloading", "Downloading... %1$d%%"),
    ("quran_download_complete", "Download complete"),
    ("quran_cancel_download", "Cancel Download"),
    ("quran_reader_options", "Reader Options"),
    ("quran_text_size", "Arabic Font Size"),
    ("quran_translation_toggle", "Show Translation"),
    ("quran_night_mode_toggle", "Night Reading Mode"),
    ("quran_khatm_planner", "Khatm Planner"),
    ("quran_word_by_word", "Word-by-Word Analysis"),
    ("quran_root_word", "Root: %1$s"),
    ("quran_lemma", "Lemma: %1$s"),
    ("quran_grammar", "Grammar: %1$s"),
    ("quran_occurrence_count", "Occurs %1$d times in Quran"),
    ("quran_daily_goal", "Daily Goal"),
    ("quran_daily_goal_pages", "%1$d pages/day"),
    ("quran_no_bookmarks", "No bookmarked verses yet."),
    ("quran_no_results", "No surahs match your search."),
    ("quran_read_surah", "Read Surah"),
    ("quran_play_audio", "Play Audio"),

    # Explore, Dua, Adhkar, Names, Calendar
    ("explore_title", "Explore"),
    ("explore_dua_library", "Dua Library"),
    ("explore_daily_adhkar", "Daily Adhkar"),
    ("explore_names_of_allah", "99 Names of Allah"),
    ("explore_names_subtitle", "The 99 Beautiful Names (Asma-ul-Husna)"),
    ("explore_islamic_calendar", "Islamic Calendar"),
    ("explore_search_hint", "Search Duas, Adhkar, Names..."),
    ("dua_categories", "Categories"),
    ("dua_all_duas", "All Duas"),
    ("dua_bookmarked", "Saved Duas"),
    ("dua_reference", "Reference: %1$s"),
    ("adhkar_morning", "Morning Adhkar"),
    ("adhkar_evening", "Evening Adhkar"),
    ("adhkar_after_prayer", "After Prayer Adhkar"),
    ("adhkar_before_sleep", "Before Sleep Adhkar"),
    ("adhkar_repeat_count", "%1$d times"),
    ("adhkar_benefit", "Virtue / Benefit"),
    ("names_meaning", "Meaning"),
    ("calendar_today", "Today"),
    ("calendar_hijri", "Hijri Date"),
    ("calendar_upcoming_events", "Upcoming Islamic Events"),
    ("calendar_white_days", "Ayyam al-Beed (White Days)"),

    # Settings & Profile
    ("settings_title", "Settings"),
    ("settings_language", "Language"),
    ("settings_general", "GENERAL"),
    ("settings_prayer", "PRAYER"),
    ("settings_appearance", "Appearance"),
    ("settings_time_format", "Time Format"),
    ("settings_city_location", "City Location"),
    ("settings_tasbeeh_haptics", "TASBEEH & HAPTICS"),
    ("settings_tap_sound", "Tap Sound"),
    ("settings_vibration", "Vibration Feedback"),
    ("settings_about_updates", "ABOUT & UPDATES"),
    ("settings_app_updates", "App Updates"),
    ("settings_credits", "Credits"),
    ("settings_prayer_notifications", "Prayer Notifications"),
    ("settings_asr_madhab", "Asr Calculation (Madhab)"),
    ("settings_hijri_convention", "Hijri Date Convention"),
    ("settings_home_cards", "Home Cards & Density"),
    ("settings_nafl_prayers", "Nafl Prayers"),
    ("settings_credits_description", "Meet the people behind FiveLight"),
    ("profile_title", "Profile"),
    ("profile_edit_name", "Edit Name"),
    ("profile_change_password", "Change Password"),
    ("profile_delete_account", "Delete Account"),
    ("profile_delete_account_confirm", "Are you sure you want to delete your account? All cloud backups and synced data will be permanently removed."),
    ("profile_signed_in_as", "Signed in as %1$s"),
    ("profile_google_account", "Google Account"),
    ("profile_email_account", "Email Account"),
    ("profile_sign_in_prompt", "Sign in or register"),

    # Cloud Sync & Backup & Updater
    ("sync_title", "Cloud Synchronization"),
    ("sync_status_synced", "All data synced"),
    ("sync_status_syncing", "Syncing changes..."),
    ("sync_status_offline", "Offline - changes queued"),
    ("sync_last_synced", "Last synced: %1$s"),
    ("backup_title", "Google Drive Backup"),
    ("backup_now", "Back Up Now"),
    ("backup_restore", "Restore from Backup"),
    ("backup_auto_frequency", "Auto Backup Frequency"),
    ("backup_last_backup", "Last backup: %1$s"),
    ("backup_in_progress", "Backing up..."),
    ("backup_restore_in_progress", "Restoring data..."),
    ("backup_success", "Backup completed successfully"),
    ("backup_restore_success", "Data restored successfully"),
    ("updater_title", "App Updates"),
    ("updater_current_version", "v%1$s (Build %2$d)"),
    ("updater_check_now", "Check for Updates"),
    ("updater_checking", "Checking for updates..."),
    ("updater_up_to_date", "FiveLight is up to date"),
    ("updater_update_available", "Update Available"),
    ("updater_update_now", "Update Now"),
    ("updater_downloading", "Downloading update... %1$d%%"),
    ("updater_install", "Install Update"),
    ("updater_official_build", "Official Release Build"),

    # Smart Notifications
    ("notif_prayer_time", "It is time for %1$s (%2$s)"),
    ("notif_pre_prayer_prep", "%1$s in %2$d minutes"),
    ("notif_action_mark_prayed", "Mark Prayed"),
    ("notif_action_snooze", "Snooze (10m)"),
    ("notif_permission_required", "Notification Permission Required"),
    ("notif_permission_desc", "To receive prayer time alerts and spiritual reminders, please enable notifications."),
    ("notif_calm_desc", "Calm, contextual notifications for prayer times, pre-prayer preparation, and voluntary windows."),

    # Language Names
    ("language_english", "English"),
    ("language_hindi_urdu", "हिंदी"),
    ("language_urdu", "اردو"),
    ("language_roman_urdu", "Roman Urdu")
]

def escape_xml(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "\\'").replace('"', '\\"')

def generate_xml_content():
    lines = ['<?xml version="1.0" encoding="utf-8"?>', '<resources>']
    for key, val in STRING_DEFINITIONS:
        escaped = escape_xml(val)
        lines.append(f'    <string name="{key}">{escaped}</string>')
    lines.append('</resources>\n')
    return "\n".join(lines)

targets = [
    "app/src/main/res/values/strings.xml",
    "app/src/main/res/values-en/strings.xml",
    "app/src/main/res/values-b+ur+Deva/strings.xml",
    "app/src/main/res/values-b+ur+Arab/strings.xml",
    "app/src/main/res/values-ur/strings.xml",
    "app/src/main/res/values-b+ur+Latn/strings.xml"
]

xml_data = generate_xml_content()
for path in targets:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(xml_data)
    print(f"Updated {path} with {len(STRING_DEFINITIONS)} strings.")
