package com.example.data.auth

import android.content.Context
import android.util.Log
import androidx.credentials.Credential
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseAuthException
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withContext

sealed class GoogleAuthException(message: String, cause: Throwable? = null) : Exception(message, cause) {
    object Cancelled : GoogleAuthException("Sign-in cancelled")
    class ConfigurationError(message: String) : GoogleAuthException(message)
    class ProviderError(message: String, cause: Throwable? = null) : GoogleAuthException(message, cause)
    class NoAccountsAvailable(message: String) : GoogleAuthException(message)
}

class AuthRepository(private val context: Context) {

    private val firebaseAuth: FirebaseAuth by lazy {
        try {
            if (FirebaseApp.getApps(context).isEmpty()) {
                FirebaseApp.initializeApp(context)
            }
        } catch (_: Exception) {}
        FirebaseAuth.getInstance()
    }
    private val prefs = context.getSharedPreferences("fivelight_prefs", Context.MODE_PRIVATE)

    private val _hasSeenAccountPrompt = MutableStateFlow(
        prefs.getBoolean("has_seen_account_prompt", false)
    )
    val hasSeenAccountPrompt: StateFlow<Boolean> = _hasSeenAccountPrompt.asStateFlow()

    private val _currentUser = MutableStateFlow<FirebaseUser?>(
        try {
            if (FirebaseApp.getApps(context).isEmpty()) {
                FirebaseApp.initializeApp(context)
            }
            firebaseAuth.currentUser
        } catch (_: Exception) {
            null
        }
    )
    val currentUser: StateFlow<FirebaseUser?> = _currentUser.asStateFlow()

    init {
        try {
            if (FirebaseApp.getApps(context).isEmpty()) {
                FirebaseApp.initializeApp(context)
            }
            firebaseAuth.addAuthStateListener { auth ->
                _currentUser.value = auth.currentUser
            }
        } catch (_: Exception) {}
    }

    fun setHasSeenAccountPrompt(seen: Boolean = true) {
        _hasSeenAccountPrompt.value = seen
        prefs.edit().putBoolean("has_seen_account_prompt", seen).apply()
    }

    suspend fun signInWithEmail(email: String, password: String): Result<FirebaseUser> = withContext(Dispatchers.IO) {
        try {
            val authResult = firebaseAuth.signInWithEmailAndPassword(email.trim(), password).await()
            val user = authResult.user ?: throw Exception("Sign in succeeded but user is null")
            _currentUser.value = user
            Result.success(user)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun registerWithEmail(email: String, password: String): Result<FirebaseUser> = withContext(Dispatchers.IO) {
        try {
            val authResult = firebaseAuth.createUserWithEmailAndPassword(email.trim(), password).await()
            val user = authResult.user ?: throw Exception("Registration succeeded but user is null")
            _currentUser.value = user
            Result.success(user)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun sendPasswordReset(email: String): Result<Unit> = withContext(Dispatchers.IO) {
        try {
            firebaseAuth.sendPasswordResetEmail(email.trim()).await()
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun signInWithGoogle(activityContext: Context): Result<FirebaseUser> = withContext(Dispatchers.IO) {
        val tag = "AuthRepository"
        try {
            // 1. Resolve Server Web Client ID dynamically from resources (generated by google-services.json)
            val resId = activityContext.resources.getIdentifier("default_web_client_id", "string", activityContext.packageName)
            val webClientId = if (resId != 0) {
                try {
                    activityContext.getString(resId).trim().takeIf { it.isNotBlank() }
                } catch (e: Exception) {
                    Log.w(tag, "Failed to read default_web_client_id string resource", e)
                    null
                }
            } else {
                // Fallback to project number or default if available
                "985622795249-fivelight.apps.googleusercontent.com".takeIf { it.isNotBlank() }
            }

            if (webClientId.isNullOrBlank()) {
                Log.e(tag, "Google Sign-In configuration error: default_web_client_id resource not found or empty.")
                return@withContext Result.failure(
                    GoogleAuthException.ConfigurationError(
                        "Google Sign-In is not configured. Missing default_web_client_id."
                    )
                )
            }

            val credentialManager = CredentialManager.create(activityContext)

            // 2. Initial attempt: query for previously authorized accounts (fast path for returning users)
            val initialOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(true)
                .setServerClientId(webClientId)
                .setAutoSelectEnabled(false)
                .build()

            val initialRequest = GetCredentialRequest.Builder()
                .addCredentialOption(initialOption)
                .build()

            val credential = try {
                val result = credentialManager.getCredential(activityContext, initialRequest)
                result.credential
            } catch (e: GetCredentialCancellationException) {
                Log.d(tag, "Google Sign-In cancelled by user on initial attempt")
                return@withContext Result.failure(GoogleAuthException.Cancelled)
            } catch (e: NoCredentialException) {
                // No authorized credential on first attempt -> automatically retry with filterByAuthorizedAccounts(false)
                Log.d(tag, "No authorized Google credential on first attempt. Retrying with filterByAuthorizedAccounts=false")
                retryWithAccountChooser(activityContext, credentialManager, webClientId)
            } catch (e: GetCredentialException) {
                val isNoCred = e is NoCredentialException ||
                        e.type.contains("no_credential", ignoreCase = true) ||
                        e.message?.contains("no credentials", ignoreCase = true) == true
                if (isNoCred) {
                    Log.d(tag, "GetCredentialException indicates no credentials. Retrying with filterByAuthorizedAccounts=false")
                    retryWithAccountChooser(activityContext, credentialManager, webClientId)
                } else {
                    Log.e(tag, "Credential provider failure: ${e.javaClass.name}: ${e.message}", e)
                    return@withContext Result.failure(
                        GoogleAuthException.ProviderError(
                            "Google Sign-In is unavailable. Please check Google Play services."
                        )
                    )
                }
            }

            if (credential == null) {
                return@withContext Result.failure(GoogleAuthException.Cancelled)
            }

            // 3. Extract Google ID Token and authenticate with Firebase
            if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val idToken = googleIdTokenCredential.idToken
                val authCredential = GoogleAuthProvider.getCredential(idToken, null)
                val authResult = firebaseAuth.signInWithCredential(authCredential).await()
                val user = authResult.user ?: throw Exception("Google sign in succeeded but user profile is null")
                _currentUser.value = user
                Result.success(user)
            } else {
                Log.e(tag, "Unsupported credential type: ${credential.type}")
                Result.failure(GoogleAuthException.ProviderError("Unsupported credential type returned from provider."))
            }
        } catch (e: GoogleAuthException.Cancelled) {
            Result.failure(e)
        } catch (e: GoogleAuthException) {
            Result.failure(e)
        } catch (e: GetCredentialCancellationException) {
            Log.d(tag, "Google Sign-In cancelled by user")
            Result.failure(GoogleAuthException.Cancelled)
        } catch (e: FirebaseAuthException) {
            Log.e(tag, "Firebase authentication failed: ${e.errorCode} - ${e.message}", e)
            Result.failure(Exception(e.localizedMessage ?: "Firebase authentication failed."))
        } catch (e: Exception) {
            Log.e(tag, "Google Sign-In error: ${e.javaClass.name}: ${e.message}", e)
            Result.failure(e)
        }
    }

    private suspend fun retryWithAccountChooser(
        activityContext: Context,
        credentialManager: CredentialManager,
        webClientId: String
    ): Credential? {
        val tag = "AuthRepository"
        val chooserOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(webClientId)
            .setAutoSelectEnabled(false)
            .build()

        val chooserRequest = GetCredentialRequest.Builder()
            .addCredentialOption(chooserOption)
            .build()

        return try {
            val result = credentialManager.getCredential(activityContext, chooserRequest)
            result.credential
        } catch (e: GetCredentialCancellationException) {
            Log.d(tag, "User cancelled Google account chooser")
            null
        } catch (e: NoCredentialException) {
            Log.w(tag, "No Google accounts available on device: ${e.message}", e)
            throw GoogleAuthException.NoAccountsAvailable(
                "No Google account found on device. Please add a Google account in system settings."
            )
        } catch (e: GetCredentialException) {
            val isNoCred = e is NoCredentialException ||
                    e.type.contains("no_credential", ignoreCase = true) ||
                    e.message?.contains("no credentials", ignoreCase = true) == true

            if (isNoCred) {
                Log.w(tag, "No Google accounts available on device: ${e.message}", e)
                throw GoogleAuthException.NoAccountsAvailable(
                    "No Google account found on device. Please add a Google account in system settings."
                )
            } else {
                Log.e(tag, "Credential provider failure during chooser: ${e.javaClass.name}: ${e.message}", e)
                throw GoogleAuthException.ProviderError(
                    "Google Sign-In is unavailable. Please check Google Play services."
                )
            }
        }
    }

    fun signOut() {
        firebaseAuth.signOut()
        _currentUser.value = null
    }

    companion object {
        @Volatile
        private var instance: AuthRepository? = null

        fun getInstance(context: Context): AuthRepository {
            return instance ?: synchronized(this) {
                instance ?: AuthRepository(context.applicationContext).also { instance = it }
            }
        }
    }
}
